# Generated by Django 4.1.1 on 2022-09-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sku',
            table='sku',
        ),
    ]
