# Generated by Django 4.1.1 on 2022-09-11 19:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_inventory', '0003_sku_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
